name: run main.py

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3  # Checkout the repo content

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py  # This should generate log.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f log.txt ]; then
            git add log.txt
            git commit -m "Update log.txt" || echo "No changes to commit"
          else
            echo "log.txt not found"
          fi

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
